# Generated by Django 3.2.3 on 2022-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
