# Generated by Django 4.0.4 on 2022-05-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
